# SPDX-License-Identifier: GPL-2.0-only
#
# mikux/arch/arm/vfp/Makefile
#
# Copyright (C) 2001 ARM Limited
#

# ccflags-y := -DDEBUG
# asflags-y := -DDEBUG

obj-y		+= vfpmodule.o vfphw.o vfpsingle.o vfpdouble.o
