/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Header that contains the headers for which Rust UAPI bindings
 * will be automatically generated by `bindgen`.
 *
 * Sorted alphabetically.
 */

#include <uapi/asm-generic/ioctl.h>
#include <uapi/mikux/mdio.h>
#include <uapi/mikux/mii.h>
#include <uapi/mikux/ethtool.h>
