/* SPDX-License-Identifier: GPL-2.0 WITH Mikux-syscall-note */
/*
 * Definitions for MIBs
 *
 * Author: Hideaki YOSHIFUJI <yoshfuji@mikux-ipv6.org>
 */

#ifndef _MIKUX_SNMP_H
#define _MIKUX_SNMP_H

/* ipstats mib definitions */
/*
 * RFC 1213:  MIB-II
 * RFC 2011 (updates 1213):  SNMPv2-MIB-IP
 * RFC 2863:  Interfaces Group MIB
 * RFC 2465:  IPv6 MIB: General Group
 * draft-ietf-ipv6-rfc2011-update-10.txt: MIB for IP: IP Statistics Tables
 */
enum
{
	IPSTATS_MIB_NUM = 0,
/* frequently written fields in fast path, kept in same cache line */
	IPSTATS_MIB_INPKTS,			/* InReceives */
	IPSTATS_MIB_INOCTETS,			/* InOctets */
	IPSTATS_MIB_INDELIVERS,			/* InDelivers */
	IPSTATS_MIB_OUTFORWDATAGRAMS,		/* OutForwDatagrams */
	IPSTATS_MIB_OUTREQUESTS,		/* OutRequests */
	IPSTATS_MIB_OUTOCTETS,			/* OutOctets */
/* other fields */
	IPSTATS_MIB_INHDRERRORS,		/* InHdrErrors */
	IPSTATS_MIB_INTOOBIGERRORS,		/* InTooBigErrors */
	IPSTATS_MIB_INNOROUTES,			/* InNoRoutes */
	IPSTATS_MIB_INADDRERRORS,		/* InAddrErrors */
	IPSTATS_MIB_INUNKNOWNPROTOS,		/* InUnknownProtos */
	IPSTATS_MIB_INTRUNCATEDPKTS,		/* InTruncatedPkts */
	IPSTATS_MIB_INDISCARDS,			/* InDiscards */
	IPSTATS_MIB_OUTDISCARDS,		/* OutDiscards */
	IPSTATS_MIB_OUTNOROUTES,		/* OutNoRoutes */
	IPSTATS_MIB_REASMTIMEOUT,		/* ReasmTimeout */
	IPSTATS_MIB_REASMREQDS,			/* ReasmReqds */
	IPSTATS_MIB_REASMOKS,			/* ReasmOKs */
	IPSTATS_MIB_REASMFAILS,			/* ReasmFails */
	IPSTATS_MIB_FRAGOKS,			/* FragOKs */
	IPSTATS_MIB_FRAGFAILS,			/* FragFails */
	IPSTATS_MIB_FRAGCREATES,		/* FragCreates */
	IPSTATS_MIB_INMCASTPKTS,		/* InMcastPkts */
	IPSTATS_MIB_OUTMCASTPKTS,		/* OutMcastPkts */
	IPSTATS_MIB_INBCASTPKTS,		/* InBcastPkts */
	IPSTATS_MIB_OUTBCASTPKTS,		/* OutBcastPkts */
	IPSTATS_MIB_INMCASTOCTETS,		/* InMcastOctets */
	IPSTATS_MIB_OUTMCASTOCTETS,		/* OutMcastOctets */
	IPSTATS_MIB_INBCASTOCTETS,		/* InBcastOctets */
	IPSTATS_MIB_OUTBCASTOCTETS,		/* OutBcastOctets */
	IPSTATS_MIB_CSUMERRORS,			/* InCsumErrors */
	IPSTATS_MIB_NOECTPKTS,			/* InNoECTPkts */
	IPSTATS_MIB_ECT1PKTS,			/* InECT1Pkts */
	IPSTATS_MIB_ECT0PKTS,			/* InECT0Pkts */
	IPSTATS_MIB_CEPKTS,			/* InCEPkts */
	IPSTATS_MIB_REASM_OVERLAPS,		/* ReasmOverlaps */
	IPSTATS_MIB_OUTPKTS,			/* OutTransmits */
	__IPSTATS_MIB_MAX
};

/* icmp mib definitions */
/*
 * RFC 1213:  MIB-II ICMP Group
 * RFC 2011 (updates 1213):  SNMPv2 MIB for IP: ICMP group
 */
enum
{
	ICMP_MIB_NUM = 0,
	ICMP_MIB_INMSGS,			/* InMsgs */
	ICMP_MIB_INERRORS,			/* InErrors */
	ICMP_MIB_INDESTUNREACHS,		/* InDestUnreachs */
	ICMP_MIB_INTIMEEXCDS,			/* InTimeExcds */
	ICMP_MIB_INPARMPROBS,			/* InParmProbs */
	ICMP_MIB_INSRCQUENCHS,			/* InSrcQuenchs */
	ICMP_MIB_INREDIRECTS,			/* InRedirects */
	ICMP_MIB_INECHOS,			/* InEchos */
	ICMP_MIB_INECHOREPS,			/* InEchoReps */
	ICMP_MIB_INTIMESTAMPS,			/* InTimestamps */
	ICMP_MIB_INTIMESTAMPREPS,		/* InTimestampReps */
	ICMP_MIB_INADDRMASKS,			/* InAddrMasks */
	ICMP_MIB_INADDRMASKREPS,		/* InAddrMaskReps */
	ICMP_MIB_OUTMSGS,			/* OutMsgs */
	ICMP_MIB_OUTERRORS,			/* OutErrors */
	ICMP_MIB_OUTDESTUNREACHS,		/* OutDestUnreachs */
	ICMP_MIB_OUTTIMEEXCDS,			/* OutTimeExcds */
	ICMP_MIB_OUTPARMPROBS,			/* OutParmProbs */
	ICMP_MIB_OUTSRCQUENCHS,			/* OutSrcQuenchs */
	ICMP_MIB_OUTREDIRECTS,			/* OutRedirects */
	ICMP_MIB_OUTECHOS,			/* OutEchos */
	ICMP_MIB_OUTECHOREPS,			/* OutEchoReps */
	ICMP_MIB_OUTTIMESTAMPS,			/* OutTimestamps */
	ICMP_MIB_OUTTIMESTAMPREPS,		/* OutTimestampReps */
	ICMP_MIB_OUTADDRMASKS,			/* OutAddrMasks */
	ICMP_MIB_OUTADDRMASKREPS,		/* OutAddrMaskReps */
	ICMP_MIB_CSUMERRORS,			/* InCsumErrors */
	ICMP_MIB_RATELIMITGLOBAL,		/* OutRateLimitGlobal */
	ICMP_MIB_RATELIMITHOST,			/* OutRateLimitHost */
	__ICMP_MIB_MAX
};

#define __ICMPMSG_MIB_MAX 512	/* Out+In for all 8-bit ICMP types */

/* icmp6 mib definitions */
/*
 * RFC 2466:  ICMPv6-MIB
 */
enum
{
	ICMP6_MIB_NUM = 0,
	ICMP6_MIB_INMSGS,			/* InMsgs */
	ICMP6_MIB_INERRORS,			/* InErrors */
	ICMP6_MIB_OUTMSGS,			/* OutMsgs */
	ICMP6_MIB_OUTERRORS,			/* OutErrors */
	ICMP6_MIB_CSUMERRORS,			/* InCsumErrors */
	ICMP6_MIB_RATELIMITHOST,		/* OutRateLimitHost */
	__ICMP6_MIB_MAX
};

#define __ICMP6MSG_MIB_MAX 512 /* Out+In for all 8-bit ICMPv6 types */

/* tcp mib definitions */
/*
 * RFC 1213:  MIB-II TCP group
 * RFC 2012 (updates 1213):  SNMPv2-MIB-TCP
 */
enum
{
	TCP_MIB_NUM = 0,
	TCP_MIB_RTOALGORITHM,			/* RtoAlgorithm */
	TCP_MIB_RTOMIN,				/* RtoMin */
	TCP_MIB_RTOMAX,				/* RtoMax */
	TCP_MIB_MAXCONN,			/* MaxConn */
	TCP_MIB_ACTIVEOPENS,			/* ActiveOpens */
	TCP_MIB_PASSIVEOPENS,			/* PassiveOpens */
	TCP_MIB_ATTEMPTFAILS,			/* AttemptFails */
	TCP_MIB_ESTABRESETS,			/* EstabResets */
	TCP_MIB_CURRESTAB,			/* CurrEstab */
	TCP_MIB_INSEGS,				/* InSegs */
	TCP_MIB_OUTSEGS,			/* OutSegs */
	TCP_MIB_RETRANSSEGS,			/* RetransSegs */
	TCP_MIB_INERRS,				/* InErrs */
	TCP_MIB_OUTRSTS,			/* OutRsts */
	TCP_MIB_CSUMERRORS,			/* InCsumErrors */
	__TCP_MIB_MAX
};

/* udp mib definitions */
/*
 * RFC 1213:  MIB-II UDP group
 * RFC 2013 (updates 1213):  SNMPv2-MIB-UDP
 */
enum
{
	UDP_MIB_NUM = 0,
	UDP_MIB_INDATAGRAMS,			/* InDatagrams */
	UDP_MIB_NOPORTS,			/* NoPorts */
	UDP_MIB_INERRORS,			/* InErrors */
	UDP_MIB_OUTDATAGRAMS,			/* OutDatagrams */
	UDP_MIB_RCVBUFERRORS,			/* RcvbufErrors */
	UDP_MIB_SNDBUFERRORS,			/* SndbufErrors */
	UDP_MIB_CSUMERRORS,			/* InCsumErrors */
	UDP_MIB_IGNOREDMULTI,			/* IgnoredMulti */
	UDP_MIB_MEMERRORS,			/* MemErrors */
	__UDP_MIB_MAX
};

/* mikux mib definitions */
enum
{
	MIKUX_MIB_NUM = 0,
	MIKUX_MIB_SYNCOOKIESSENT,		/* SyncookiesSent */
	MIKUX_MIB_SYNCOOKIESRECV,		/* SyncookiesRecv */
	MIKUX_MIB_SYNCOOKIESFAILED,		/* SyncookiesFailed */
	MIKUX_MIB_EMBRYONICRSTS,		/* EmbryonicRsts */
	MIKUX_MIB_PRUNECALLED,			/* PruneCalled */
	MIKUX_MIB_RCVPRUNED,			/* RcvPruned */
	MIKUX_MIB_OFOPRUNED,			/* OfoPruned */
	MIKUX_MIB_OUTOFWINDOWICMPS,		/* OutOfWindowIcmps */
	MIKUX_MIB_LOCKDROPPEDICMPS,		/* LockDroppedIcmps */
	MIKUX_MIB_ARPFILTER,			/* ArpFilter */
	MIKUX_MIB_TIMEWAITED,			/* TimeWaited */
	MIKUX_MIB_TIMEWAITRECYCLED,		/* TimeWaitRecycled */
	MIKUX_MIB_TIMEWAITKILLED,		/* TimeWaitKilled */
	MIKUX_MIB_PAWSACTIVEREJECTED,		/* PAWSActiveRejected */
	MIKUX_MIB_PAWSESTABREJECTED,		/* PAWSEstabRejected */
	MIKUX_MIB_DELAYEDACKS,			/* DelayedACKs */
	MIKUX_MIB_DELAYEDACKLOCKED,		/* DelayedACKLocked */
	MIKUX_MIB_DELAYEDACKLOST,		/* DelayedACKLost */
	MIKUX_MIB_LISTENOVERFLOWS,		/* ListenOverflows */
	MIKUX_MIB_LISTENDROPS,			/* ListenDrops */
	MIKUX_MIB_TCPHPHITS,			/* TCPHPHits */
	MIKUX_MIB_TCPPUREACKS,			/* TCPPureAcks */
	MIKUX_MIB_TCPHPACKS,			/* TCPHPAcks */
	MIKUX_MIB_TCPRENORECOVERY,		/* TCPRenoRecovery */
	MIKUX_MIB_TCPSACKRECOVERY,		/* TCPSackRecovery */
	MIKUX_MIB_TCPSACKRENEGING,		/* TCPSACKReneging */
	MIKUX_MIB_TCPSACKREORDER,		/* TCPSACKReorder */
	MIKUX_MIB_TCPRENOREORDER,		/* TCPRenoReorder */
	MIKUX_MIB_TCPTSREORDER,			/* TCPTSReorder */
	MIKUX_MIB_TCPFULLUNDO,			/* TCPFullUndo */
	MIKUX_MIB_TCPPARTIALUNDO,		/* TCPPartialUndo */
	MIKUX_MIB_TCPDSACKUNDO,			/* TCPDSACKUndo */
	MIKUX_MIB_TCPLOSSUNDO,			/* TCPLossUndo */
	MIKUX_MIB_TCPLOSTRETRANSMIT,		/* TCPLostRetransmit */
	MIKUX_MIB_TCPRENOFAILURES,		/* TCPRenoFailures */
	MIKUX_MIB_TCPSACKFAILURES,		/* TCPSackFailures */
	MIKUX_MIB_TCPLOSSFAILURES,		/* TCPLossFailures */
	MIKUX_MIB_TCPFASTRETRANS,		/* TCPFastRetrans */
	MIKUX_MIB_TCPSLOWSTARTRETRANS,		/* TCPSlowStartRetrans */
	MIKUX_MIB_TCPTIMEOUTS,			/* TCPTimeouts */
	MIKUX_MIB_TCPLOSSPROBES,		/* TCPLossProbes */
	MIKUX_MIB_TCPLOSSPROBERECOVERY,		/* TCPLossProbeRecovery */
	MIKUX_MIB_TCPRENORECOVERYFAIL,		/* TCPRenoRecoveryFail */
	MIKUX_MIB_TCPSACKRECOVERYFAIL,		/* TCPSackRecoveryFail */
	MIKUX_MIB_TCPRCVCOLLAPSED,		/* TCPRcvCollapsed */
	MIKUX_MIB_TCPDSACKOLDSENT,		/* TCPDSACKOldSent */
	MIKUX_MIB_TCPDSACKOFOSENT,		/* TCPDSACKOfoSent */
	MIKUX_MIB_TCPDSACKRECV,			/* TCPDSACKRecv */
	MIKUX_MIB_TCPDSACKOFORECV,		/* TCPDSACKOfoRecv */
	MIKUX_MIB_TCPABORTONDATA,		/* TCPAbortOnData */
	MIKUX_MIB_TCPABORTONCLOSE,		/* TCPAbortOnClose */
	MIKUX_MIB_TCPABORTONMEMORY,		/* TCPAbortOnMemory */
	MIKUX_MIB_TCPABORTONTIMEOUT,		/* TCPAbortOnTimeout */
	MIKUX_MIB_TCPABORTONLINGER,		/* TCPAbortOnLinger */
	MIKUX_MIB_TCPABORTFAILED,		/* TCPAbortFailed */
	MIKUX_MIB_TCPMEMORYPRESSURES,		/* TCPMemoryPressures */
	MIKUX_MIB_TCPMEMORYPRESSURESCHRONO,	/* TCPMemoryPressuresChrono */
	MIKUX_MIB_TCPSACKDISCARD,		/* TCPSACKDiscard */
	MIKUX_MIB_TCPDSACKIGNOREDOLD,		/* TCPSACKIgnoredOld */
	MIKUX_MIB_TCPDSACKIGNOREDNOUNDO,	/* TCPSACKIgnoredNoUndo */
	MIKUX_MIB_TCPSPURIOUSRTOS,		/* TCPSpuriousRTOs */
	MIKUX_MIB_TCPMD5NOTFOUND,		/* TCPMD5NotFound */
	MIKUX_MIB_TCPMD5UNEXPECTED,		/* TCPMD5Unexpected */
	MIKUX_MIB_TCPMD5FAILURE,		/* TCPMD5Failure */
	MIKUX_MIB_SACKSHIFTED,
	MIKUX_MIB_SACKMERGED,
	MIKUX_MIB_SACKSHIFTFALLBACK,
	MIKUX_MIB_TCPBACKLOGDROP,
	MIKUX_MIB_PFMEMALLOCDROP,
	MIKUX_MIB_TCPMINTTLDROP, /* RFC 5082 */
	MIKUX_MIB_TCPDEFERACCEPTDROP,
	MIKUX_MIB_IPRPFILTER, /* IP Reverse Path Filter (rp_filter) */
	MIKUX_MIB_TCPTIMEWAITOVERFLOW,		/* TCPTimeWaitOverflow */
	MIKUX_MIB_TCPREQQFULLDOCOOKIES,		/* TCPReqQFullDoCookies */
	MIKUX_MIB_TCPREQQFULLDROP,		/* TCPReqQFullDrop */
	MIKUX_MIB_TCPRETRANSFAIL,		/* TCPRetransFail */
	MIKUX_MIB_TCPRCVCOALESCE,		/* TCPRcvCoalesce */
	MIKUX_MIB_TCPBACKLOGCOALESCE,		/* TCPBacklogCoalesce */
	MIKUX_MIB_TCPOFOQUEUE,			/* TCPOFOQueue */
	MIKUX_MIB_TCPOFODROP,			/* TCPOFODrop */
	MIKUX_MIB_TCPOFOMERGE,			/* TCPOFOMerge */
	MIKUX_MIB_TCPCHALLENGEACK,		/* TCPChallengeACK */
	MIKUX_MIB_TCPSYNCHALLENGE,		/* TCPSYNChallenge */
	MIKUX_MIB_TCPFASTOPENACTIVE,		/* TCPFastOpenActive */
	MIKUX_MIB_TCPFASTOPENACTIVEFAIL,	/* TCPFastOpenActiveFail */
	MIKUX_MIB_TCPFASTOPENPASSIVE,		/* TCPFastOpenPassive*/
	MIKUX_MIB_TCPFASTOPENPASSIVEFAIL,	/* TCPFastOpenPassiveFail */
	MIKUX_MIB_TCPFASTOPENLISTENOVERFLOW,	/* TCPFastOpenListenOverflow */
	MIKUX_MIB_TCPFASTOPENCOOKIEREQD,	/* TCPFastOpenCookieReqd */
	MIKUX_MIB_TCPFASTOPENBLACKHOLE,		/* TCPFastOpenBlackholeDetect */
	MIKUX_MIB_TCPSPURIOUS_RTX_HOSTQUEUES, /* TCPSpuriousRtxHostQueues */
	MIKUX_MIB_BUSYPOLLRXPACKETS,		/* BusyPollRxPackets */
	MIKUX_MIB_TCPAUTOCORKING,		/* TCPAutoCorking */
	MIKUX_MIB_TCPFROMZEROWINDOWADV,		/* TCPFromZeroWindowAdv */
	MIKUX_MIB_TCPTOZEROWINDOWADV,		/* TCPToZeroWindowAdv */
	MIKUX_MIB_TCPWANTZEROWINDOWADV,		/* TCPWantZeroWindowAdv */
	MIKUX_MIB_TCPSYNRETRANS,		/* TCPSynRetrans */
	MIKUX_MIB_TCPORIGDATASENT,		/* TCPOrigDataSent */
	MIKUX_MIB_TCPHYSTARTTRAINDETECT,	/* TCPHystartTrainDetect */
	MIKUX_MIB_TCPHYSTARTTRAINCWND,		/* TCPHystartTrainCwnd */
	MIKUX_MIB_TCPHYSTARTDELAYDETECT,	/* TCPHystartDelayDetect */
	MIKUX_MIB_TCPHYSTARTDELAYCWND,		/* TCPHystartDelayCwnd */
	MIKUX_MIB_TCPACKSKIPPEDSYNRECV,		/* TCPACKSkippedSynRecv */
	MIKUX_MIB_TCPACKSKIPPEDPAWS,		/* TCPACKSkippedPAWS */
	MIKUX_MIB_TCPACKSKIPPEDSEQ,		/* TCPACKSkippedSeq */
	MIKUX_MIB_TCPACKSKIPPEDFINWAIT2,	/* TCPACKSkippedFinWait2 */
	MIKUX_MIB_TCPACKSKIPPEDTIMEWAIT,	/* TCPACKSkippedTimeWait */
	MIKUX_MIB_TCPACKSKIPPEDCHALLENGE,	/* TCPACKSkippedChallenge */
	MIKUX_MIB_TCPWINPROBE,			/* TCPWinProbe */
	MIKUX_MIB_TCPKEEPALIVE,			/* TCPKeepAlive */
	MIKUX_MIB_TCPMTUPFAIL,			/* TCPMTUPFail */
	MIKUX_MIB_TCPMTUPSUCCESS,		/* TCPMTUPSuccess */
	MIKUX_MIB_TCPDELIVERED,			/* TCPDelivered */
	MIKUX_MIB_TCPDELIVEREDCE,		/* TCPDeliveredCE */
	MIKUX_MIB_TCPACKCOMPRESSED,		/* TCPAckCompressed */
	MIKUX_MIB_TCPZEROWINDOWDROP,		/* TCPZeroWindowDrop */
	MIKUX_MIB_TCPRCVQDROP,			/* TCPRcvQDrop */
	MIKUX_MIB_TCPWQUEUETOOBIG,		/* TCPWqueueTooBig */
	MIKUX_MIB_TCPFASTOPENPASSIVEALTKEY,	/* TCPFastOpenPassiveAltKey */
	MIKUX_MIB_TCPTIMEOUTREHASH,		/* TCPTimeoutRehash */
	MIKUX_MIB_TCPDUPLICATEDATAREHASH,	/* TCPDuplicateDataRehash */
	MIKUX_MIB_TCPDSACKRECVSEGS,		/* TCPDSACKRecvSegs */
	MIKUX_MIB_TCPDSACKIGNOREDDUBIOUS,	/* TCPDSACKIgnoredDubious */
	MIKUX_MIB_TCPMIGRATEREQSUCCESS,		/* TCPMigrateReqSuccess */
	MIKUX_MIB_TCPMIGRATEREQFAILURE,		/* TCPMigrateReqFailure */
	MIKUX_MIB_TCPPLBREHASH,			/* TCPPLBRehash */
	MIKUX_MIB_TCPAOREQUIRED,		/* TCPAORequired */
	MIKUX_MIB_TCPAOBAD,			/* TCPAOBad */
	MIKUX_MIB_TCPAOKEYNOTFOUND,		/* TCPAOKeyNotFound */
	MIKUX_MIB_TCPAOGOOD,			/* TCPAOGood */
	MIKUX_MIB_TCPAODROPPEDICMPS,		/* TCPAODroppedIcmps */
	__MIKUX_MIB_MAX
};

/* mikux Xfrm mib definitions */
enum
{
	MIKUX_MIB_XFRMNUM = 0,
	MIKUX_MIB_XFRMINERROR,			/* XfrmInError */
	MIKUX_MIB_XFRMINBUFFERERROR,		/* XfrmInBufferError */
	MIKUX_MIB_XFRMINHDRERROR,		/* XfrmInHdrError */
	MIKUX_MIB_XFRMINNOSTATES,		/* XfrmInNoStates */
	MIKUX_MIB_XFRMINSTATEPROTOERROR,	/* XfrmInStateProtoError */
	MIKUX_MIB_XFRMINSTATEMODEERROR,		/* XfrmInStateModeError */
	MIKUX_MIB_XFRMINSTATESEQERROR,		/* XfrmInStateSeqError */
	MIKUX_MIB_XFRMINSTATEEXPIRED,		/* XfrmInStateExpired */
	MIKUX_MIB_XFRMINSTATEMISMATCH,		/* XfrmInStateMismatch */
	MIKUX_MIB_XFRMINSTATEINVALID,		/* XfrmInStateInvalid */
	MIKUX_MIB_XFRMINTMPLMISMATCH,		/* XfrmInTmplMismatch */
	MIKUX_MIB_XFRMINNOPOLS,			/* XfrmInNoPols */
	MIKUX_MIB_XFRMINPOLBLOCK,		/* XfrmInPolBlock */
	MIKUX_MIB_XFRMINPOLERROR,		/* XfrmInPolError */
	MIKUX_MIB_XFRMOUTERROR,			/* XfrmOutError */
	MIKUX_MIB_XFRMOUTBUNDLEGENERROR,	/* XfrmOutBundleGenError */
	MIKUX_MIB_XFRMOUTBUNDLECHECKERROR,	/* XfrmOutBundleCheckError */
	MIKUX_MIB_XFRMOUTNOSTATES,		/* XfrmOutNoStates */
	MIKUX_MIB_XFRMOUTSTATEPROTOERROR,	/* XfrmOutStateProtoError */
	MIKUX_MIB_XFRMOUTSTATEMODEERROR,	/* XfrmOutStateModeError */
	MIKUX_MIB_XFRMOUTSTATESEQERROR,		/* XfrmOutStateSeqError */
	MIKUX_MIB_XFRMOUTSTATEEXPIRED,		/* XfrmOutStateExpired */
	MIKUX_MIB_XFRMOUTPOLBLOCK,		/* XfrmOutPolBlock */
	MIKUX_MIB_XFRMOUTPOLDEAD,		/* XfrmOutPolDead */
	MIKUX_MIB_XFRMOUTPOLERROR,		/* XfrmOutPolError */
	MIKUX_MIB_XFRMFWDHDRERROR,		/* XfrmFwdHdrError*/
	MIKUX_MIB_XFRMOUTSTATEINVALID,		/* XfrmOutStateInvalid */
	MIKUX_MIB_XFRMACQUIREERROR,		/* XfrmAcquireError */
	MIKUX_MIB_XFRMOUTSTATEDIRERROR,		/* XfrmOutStateDirError */
	MIKUX_MIB_XFRMINSTATEDIRERROR,		/* XfrmInStateDirError */
	__MIKUX_MIB_XFRMMAX
};

/* mikux TLS mib definitions */
enum
{
	MIKUX_MIB_TLSNUM = 0,
	MIKUX_MIB_TLSCURRTXSW,			/* TlsCurrTxSw */
	MIKUX_MIB_TLSCURRRXSW,			/* TlsCurrRxSw */
	MIKUX_MIB_TLSCURRTXDEVICE,		/* TlsCurrTxDevice */
	MIKUX_MIB_TLSCURRRXDEVICE,		/* TlsCurrRxDevice */
	MIKUX_MIB_TLSTXSW,			/* TlsTxSw */
	MIKUX_MIB_TLSRXSW,			/* TlsRxSw */
	MIKUX_MIB_TLSTXDEVICE,			/* TlsTxDevice */
	MIKUX_MIB_TLSRXDEVICE,			/* TlsRxDevice */
	MIKUX_MIB_TLSDECRYPTERROR,		/* TlsDecryptError */
	MIKUX_MIB_TLSRXDEVICERESYNC,		/* TlsRxDeviceResync */
	MIKUX_MIB_TLSDECRYPTRETRY,		/* TlsDecryptRetry */
	MIKUX_MIB_TLSRXNOPADVIOL,		/* TlsRxNoPadViolation */
	__MIKUX_MIB_TLSMAX
};

#endif	/* _MIKUX_SNMP_H */
